// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVbMcM733Qz5wQ4wsOHfnaIxYhoBRMCwk',
    appId: '1:308421722887:web:afd5c80800141f040b3ba2',
    messagingSenderId: '308421722887',
    projectId: 'mybike02-ec694',
    authDomain: 'mybike02-ec694.firebaseapp.com',
    databaseURL: 'https://mybike02-ec694-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybike02-ec694.firebasestorage.app',
    measurementId: 'G-VVC4ZP2TTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiBXvhX4YenKelpFUA30_R5p_OVkbHy8o',
    appId: '1:308421722887:android:11873da5368189bc0b3ba2',
    messagingSenderId: '308421722887',
    projectId: 'mybike02-ec694',
    databaseURL: 'https://mybike02-ec694-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybike02-ec694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMV23kyiVtVG0Ic0ROaBWYdo7QkmMrOM',
    appId: '1:308421722887:ios:abd50ffbf613c2d20b3ba2',
    messagingSenderId: '308421722887',
    projectId: 'mybike02-ec694',
    databaseURL: 'https://mybike02-ec694-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybike02-ec694.firebasestorage.app',
    iosBundleId: 'com.example.mybike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiMV23kyiVtVG0Ic0ROaBWYdo7QkmMrOM',
    appId: '1:308421722887:ios:abd50ffbf613c2d20b3ba2',
    messagingSenderId: '308421722887',
    projectId: 'mybike02-ec694',
    databaseURL: 'https://mybike02-ec694-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybike02-ec694.firebasestorage.app',
    iosBundleId: 'com.example.mybike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVbMcM733Qz5wQ4wsOHfnaIxYhoBRMCwk',
    appId: '1:308421722887:web:c95d5ee0bcb130380b3ba2',
    messagingSenderId: '308421722887',
    projectId: 'mybike02-ec694',
    authDomain: 'mybike02-ec694.firebaseapp.com',
    databaseURL: 'https://mybike02-ec694-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybike02-ec694.firebasestorage.app',
    measurementId: 'G-Z3F58CVTF8',
  );
}
